safe: false
auto: false
server: false
server_port: 4000
baseurl: http://www.samsherar.co.uk/

source: .
destination: ./_site
plugins: ./_plugins

future: true
lsi: false
pygments: true
markdown: maruku
permalink: date
